swagger: "2.0"
info:
  description: "This is an API for CVEs management."
  version: "0.0.1"
  title: "CVE Management"
  contact:
    email: "infra@openeuler.org"
host: "apis.openeuler.org"
basePath: "/v1"
tags:
- name: "CVE"
  description: "Everything about CVE information"
  externalDocs:
    description: "Find out more"
    url: "http://developer.openeuler.org"
schemes:
- "https"
- "http"
paths:
  /cve:
    get:
      tags:
      - "CVE"
      summary: "Finds CVEs by special condition"
      description: "Get CVE with each detailed information"
      operationId: "getCVEs"
      produces:
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: false
        type: "array"
        items:
          type: "string"
          enum:
          - "open"
          - "fixed"
          - "inprocess"
          default: "fixed"
        collectionFormat: "multi"
      - name: "version"
        in: "query"
        description: "The fixed version that belong to is to filter"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/cve"
        400:
          description: "Invalid status value"
  /cve/{Id}:
    get:
      tags:
      - "CVE"
      summary: "Find CVE by ID"
      description: "Returns a the detailed infomation of a CVE"
      operationId: "getCVEById"
      produces:
      - "application/json"
      parameters:
      - name: "Id"
        in: "path"
        description: "ID of CVE to query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/cve"
        400:
          description: "Invalid ID supplied"
        404:
          description: "CVE not found"
definitions:
  cve:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        description: "The CVE ID that will identify for others, which is generate by NVD or other organization."
      abstract:
        type: "string"
        description: "The abstract of CVE that descripts the major information of each CVEs."
      score:
        type: "integer"
        format: "int64"
        example: "7"
        description: "The important level, which value is from 1 to 10, 10 means the most important."
      publishtime:
        type: "string"
        description: "The publish time of the CVE. format is YYYY-MM-DD hh-mm-ss."
      importance:
        type: "string"
        description: "The important level in name, which can be serious, main, generic, unimportant."
        enum:
        - "serious"
        - "main"
        - "generic"
        - "unimportant"
      description:
        type: "string"
        description: "The detailed description of a CVE, which will contain the references."
      status:
        type: "string"
        description: "The status in the cve"
        enum:
        - "open"
        - "fixed"
        - "inprocess"
